name: lorem_picsum
description: App built for Gelato.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.1 
  connectivity_plus: ^2.3.6+1 
  cupertino_icons: ^1.0.2
  dio: ^4.0.6 
  either_dart: ^0.2.0
  flutter:
    sdk: flutter
  flutter_bloc: ^7.3.3
  flutter_svg: ^1.1.3 
  freezed_annotation: ^2.1.0
  json_annotation: ^4.6.0
  provider: ^6.0.3
  retrofit: ^3.0.1+1
  shimmer: ^2.0.0 

dev_dependencies:
  bloc_test: ^8.5.0
  build_runner: ^2.2.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.1.0+1
  json_serializable: ^6.3.1
  mews_pedantic: ^0.7.0 
  mockito: ^5.3.0
  retrofit_generator: ^4.0.3+1

flutter:
  uses-material-design: true
  assets: 
    - assets/